"""initial schema with is_admin and submitted_by

Revision ID: f07b82cd0998
Revises: 
Create Date: 2026-03-08 16:16:59.243107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f07b82cd0998'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_parking_history')
    op.drop_table('major_campus_mapping')
    op.add_column('parking_spots', sa.Column('latitude', sa.Double(), nullable=True))
    op.add_column('parking_spots', sa.Column('longitude', sa.Double(), nullable=True))
    op.add_column('parking_spots', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.alter_column('parking_spots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'parking_spots', 'users', ['submitted_by'], ['user_id'])
    op.add_column('users', sa.Column('prefered_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'prefered_name')
    op.drop_constraint(None, 'parking_spots', type_='foreignkey')
    op.alter_column('parking_spots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('parking_spots', 'submitted_by')
    op.drop_column('parking_spots', 'longitude')
    op.drop_column('parking_spots', 'latitude')
    op.create_table('major_campus_mapping',
    sa.Column('mapping_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('major_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('major_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('primary_campus', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('common_buildings', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('mapping_id', name='major_campus_mapping_pkey')
    )
    op.create_table('user_parking_history',
    sa.Column('history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_campus', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('typical_arrival_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spots.spot_id'], name='user_parking_history_spot_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_parking_history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', name='user_parking_history_pkey')
    )
    # ### end Alembic commands ###
